URL = http://download.gna.org/wkhtmltopdf/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
LIBEXEC = /home/michael/Desktop/Code/pages-github/resume/_vendor/bundle/ruby/2.4.0/gems/wkhtmltopdf-installer-0.12.4.0/lib/../libexec
TARGET = /home/michael/Desktop/Code/pages-github/resume/_vendor/bundle/ruby/2.4.0/gems/wkhtmltopdf-installer-0.12.4.0/lib/../libexec/wkhtmltopdf
TMPDIR = /tmp/d20170227-11873-1r2h59j
all: unpack
install: copy clean
include Makefile.linux
include Makefile.common
